# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "vars", # <uk_2010_get>
  "values", # <uk_2010_get>
  "rowname", # <uk_2010_get>
  "value", # <uk_2010_get>
  ".", # <uk_2010_get>
  "uk_col_lab", # <uk_2010_get>
  "uk_col", # <uk_2010_get>
  "uk_row_lab", # <uk_2010_get>
  "uk_row", # <uk_2010_get>
  NULL
))
